metvars = {
    'precip': {
        'mod': {
            'geps': ['APCP_SFC_0', 'APCP', 'surface'],
        },
        'acc': True,
        'weighted': True,
        'corrected': False,
        'interpolation': 'distance weighted',
        'dp': 1,
        'offset': None,
        'std': True,
        'use_weights': 'apcp',
        'mult': None,
        'units': 'millimetres',
        'correction': 'ratio',
        'scale': 10,
        'db_name': 'apcp',
        'smF': None,
        'neg': False,
    },
    't_max': {
        'mod': {
            'geps': ['TMAX_TGL_2m', 'TMAX', '2 m above ground'],
        },
        'acc': False,
        'weighted': True,
        'corrected': True,
        'interpolation': 'distance weighted',
        'dp': 1,
        'offset': None,
        'std': True,
        'mult': None,
        'units': 'celsius',
        'correction': 'difference',
        'scale': 10,
        'db_name': 'tmpc',
        'smF': None,
        'neg': False,
    },
    't_min': {
        'mod': {
            'geps': ['TMIN_TGL_2m', 'TMIN', '2 m above ground'],
        },
        'acc': False,
        'weighted': True,
        'corrected': True,
        'interpolation': 'distance weighted',
        'dp': 1,
        'offset': None,
        'std': True,
        'mult': None,
        'units': 'celsius',
        'correction': 'difference',
        'scale': 10,
        'db_name': 'tmpc',
        'smF': None,
        'neg': False,
    },
}


# old stuff
'''
    't': {
        'mod': {
            'rdps': ['TMP_TGL_2', 'TMP', '2 m above ground'],
            'gdps': ['TMP_TGL_2', 'TMP', '2 m above ground'],
            'reps': ['TMP_TGL_2m', 'TMP', '2 m above ground'],
            'geps': ['TMP_TGL_2m', 'TMP', '2 m above ground'],
            'nam': [None, 'TMP', '2 m above ground'],
            'rap': [None, 'TMP', '2 m above ground'],
            'gfs': [None, 'TMP', '2 m above ground'],
            'sref': [None, 'TMP', '2 m above ground'],
            'gefs': [None, 'TMP', '2 m above ground'],
            'met_fr': ['TMP/2m', 'TMP', '2 m above ground'],
            'icon': ['t_2m', 'TMP', '2 m above ground'],
        },
        'acc': False,
        'weighted': True,
        'corrected': True,
        'interpolation': 'distance weighted',
        'dp': 1,
        'offset': None,
        'std': True,
        'mult': None,
        'units': 'celsius',
        'scale': 10,
        'db_name': 'tmpc',
        'smF': None,
        'neg': False,
    },

'''