metvars = {
    'precip': {
        'mod': {
            'rdps': ['APCP_SFC_0', 'APCP', 'surface'],
            'gdps': ['APCP_SFC_0', 'APCP', 'surface'],
            'reps': ['APCP_SFC_0', 'APCP', 'surface'],
            'geps': ['APCP_SFC_0', 'APCP', 'surface'],
            'nam': [None, 'APCP', 'surface'],
            'rap': [None, 'APCP', 'surface'],
            'gfs': [None, 'APCP', 'surface'],
            'sref': [None, 'APCP', 'surface'],
            'gefs': [None, 'APCP', 'surface'],
            'met_fr': ['TPRATE/surface', 'TPRATE', 'surface'],
            'icon': ['tot_prec', 'TPRATE', 'surface'],
        },
        'acc': True,
        'weighted': True,
        'corrected': False,
        'interpolation': 'distance weighted',
        'dp': 1,
        'offset': None,
        'std': True,
        'use_weights': 'apcp',
        'mult': None,
        'units': 'millimetres',
        'scale': 10,
        'db_name': 'apcp',
        'smF': None,
        'neg': False,
    },
    't': {
        'mod': {
            'rdps': ['TMP_TGL_2', 'TMP', '2 m above ground'],
            'gdps': ['TMP_TGL_2', 'TMP', '2 m above ground'],
            'reps': ['TMP_TGL_2m', 'TMP', '2 m above ground'],
            'geps': ['TMP_TGL_2m', 'TMP', '2 m above ground'],
            'nam': [None, 'TMP', '2 m above ground'],
            'rap': [None, 'TMP', '2 m above ground'],
            'gfs': [None, 'TMP', '2 m above ground'],
            'sref': [None, 'TMP', '2 m above ground'],
            'gefs': [None, 'TMP', '2 m above ground'],
            'met_fr': ['TMP/2m', 'TMP', '2 m above ground'],
            'icon': ['t_2m', 'TMP', '2 m above ground'],
        },
        'acc': False,
        'weighted': True,
        'corrected': True,
        'interpolation': 'distance weighted',
        'dp': 1,
        'offset': None,
        'std': True,
        'mult': None,
        'units': 'celsius',
        'scale': 10,
        'db_name': 'tmpc',
        'smF': None,
        'neg': False,
    },
}